# Indirect

Merubah isi dalam sell kedalam fungsi,  jdi teks yang ada dalam suatu cell akan menjadi fungsi ya? hal ini bisa di jadikan referensi misal
H1 adlah countif hasilnya 100

dengan indirect kita bisa mengambil B100 di  sheet sebelah indirect(H1)

In [ ]:
=INDIRECT("'" & "Sheet1" & "'!" & "B" & I1)

# Contoh lain
=QUERY(INDIRECT("'" & A1 & "'!" & B1), "SELECT A, B, C LIMIT " & C1)

# membuat no dengan array formula

In [ ]:
={"NO";ARRAYFORMULA(IF(B5:B<>"",ROW(B5:B)-4,""))}

# mengubah baris ke kolom

In [ ]:
=TRANSPOSE(range)

# Grafik mini dalam sell

In [ ]:
=SPARKLINE(A1:A10, {"charttype", "line"})

# Mengambil data unik saja jika ada double

In [ ]:
=UNIQUE(range)

# Find dan Search

Gunakan FIND jika Anda peduli dengan huruf besar/kecil.
Gunakan SEARCH jika Anda tidak peduli dengan huruf besar/kecil.

In [ ]:
=MID(D2,FIND(":",D2,FIND(":",D2)+1),SEARCH(IF(ISNUMBER(SEARCH("OFF",D2)),"OFF",IF(ISNUMBER(SEARCH("ON",D2)),"ON","BUKAN DEBIT")),D2)-FIND(":",D2,FIND(":",D2)+1))

"""
Adalah fungsi mencari pelaku kurset di laporan kurset
"""

# Mengakses data beda file

In [ ]:
IMPORTRANGE("link gsheet yang dituju","Nama Sheet!B4:e"

# fungsi filter : Mengambil data tertentu beda file

Contoh filenya ada di file master EDC

In [ ]:
=filter(IMPORTRANGE("link gsheet yang dituju","Nama Sheet!B4:e"),(IMPORTRANGE("linkgsheet yang dituju","Nama Sheet!F4:F")<>"EBT"))

""""
Fungsi diatas adalah mengambil file semua toko dengan keterangan yang sudah buka
""""

# Vlookup beda file

In [ ]:
VLOOKUP(B2:B,IMPORTRANGE("https://docs.google.com/spreadsheets/d/1adnS2WfILoHqcl0Q4CXJn4luPioqwGbmSZmQmxVMob0/edit?usp=sharing","MASTER TOKO!$B$4:$H"),3,0)

# Mengambil summary data dari banyak data

In [1]:
=(IFERROR(VLOOKUP($B$4:$B,QUERY(IMPORTRANGE("https://docs.google.com/spreadsheets/d/1YnwP2m7DY5k7-KabuydJTijo9vQ0bq_o0gChFW8rKPk/edit?gid=977612074#gid=977612074","Sheet2!A1:C"),"SELECT Col1, SUM(Col3) GROUP BY Col1",0),2,0),0)/DAY(TODAY()-1))

"""
Data digrouping dulu dalam data lalu di vlookup sesuai keinginan
"""

SyntaxError: invalid syntax (<ipython-input-1-b44f83137a10>, line 1)

# Mengabi data toko dan jumlah salesnya saja

In [ ]:
QUERY(IMPORTRANGE("https://docs.google.com/spreadsheets/d/1YnwP2m7DY5k7-KabuydJTijo9vQ0bq_o0gChFW8rKPk/edit?gid=977612074#gid=977612074","Sheet2!A1:C"),"SELECT Col1, SUM(Col3) GROUP BY Col1",0)

# Array formula

In [ ]:
={"AREA SPV";ARRAYFORMULA(IFERROR(IF(ISBLANK(B2:B),"",VLOOKUP(B2:B,IMPORTRANGE("https://docs.google.com/spreadsheets/d/1adnS2WfILoHqcl0Q4CXJn4luPioqwGbmSZmQmxVMob0/edit?usp=sharing","MASTER TOKO!$B$4:$H"),3,0)),"PRIBADI"))}

# Mengambil data lalu diurutkan

In [ ]:
=QUERY(PERTOKO!B4:J6382,"SELECT * ORDER BY Col9 DESC LIMIT "&Q1,0)

"""
Q1 adalah total baris yang akan di ambil, karena jika tidak ada limit makan
filternay akan rusak karna ambil data paling bawah dalam hal ini adalah bris 1000
Q1 adlah counta dari data asal
"""

# Conditional formating

In [ ]:
=RIGHT($L1210,4)="DONE"

"""
Digunakan jika data = done di warna birukan

Agar semua baris kena maka
rangenya harus kena semua misal

A1210:S2989
"""

#  Melihat data duplicate

In [ ]:
=COUNTIF($D$1:$D$1989, D1)>1

"""
Ini disimpan pada colom d formatingnya
lalau pilih formula
"""

# Membuat data dengan gabungan dari beberapa kolom

In [ ]:
# cara 1
=TEXTJOIN(", ",1,E1925:I1925)

# cara 2
Concat

# cara 3
kombinasi = +, ""

# Memisahkan tanggal bulan tahun

In [ ]:
=split(a1, "/")

# Mengambil data last 3 m

In [ ]:
=COUNTIFS('DATA CLEANING'!$A$2:$A, $B6, 'DATA CLEANING'!$J$2:$J, TEXT(EDATE(TODAY(), -1), "MMM"), 'DATA CLEANING'!$N$2:$N, "HUMAN ERROR")
+ COUNTIFS('DATA CLEANING'!$A$2:$A, $B6, 'DATA CLEANING'!$J$2:$J, TEXT(EDATE(TODAY(), -2), "MMM"), 'DATA CLEANING'!$N$2:$N, "HUMAN ERROR")
+ COUNTIFS('DATA CLEANING'!$A$2:$A, $B6, 'DATA CLEANING'!$J$2:$J, TEXT(EDATE(TODAY(), -3), "MMM"), 'DATA CLEANING'!$N$2:$N, "HUMAN ERROR")

# Edate
Fungsi EDATE digunakan untuk menghitung tanggal jatuh tempo atau tanggal di masa depan/masa lalu dengan menambahkan atau mengurangi jumlah bulan dari tanggal yang diberikan.

In [ ]:
TEXT(EDATE(TODAY(), -1), "MMM")

"""
Fungsi diatas menampilkan bulan dalam bentukan "MMM" karena -1 maka yang akan dikeluarkan adalah bulan lalu
bulan lalu)
"""

TEXT(EDATE(TODAY(), -2), "MMM") # akan keluar b2 bulan lalau


TEXT(EDATE(TODAY(), -2), "MMM") # akan keluar last 3 month